In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import average_precision_score
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1 # not used
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20

In [3]:
# Parameters
seed = 1

In [4]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [5]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [6]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [7]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [8]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [9]:
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values

In [10]:
spectral_energy = np.nansum(X_feat, axis=1)
anomaly_scores = spectral_energy

ap = average_precision_score(y_true, anomaly_scores)
print(f"Total spectral energy AP = {ap:.4f}")
sb.glue("GBG500_ap_spectral_energy", float(ap))

ranks = pd.Series(anomaly_scores).rank(ascending=False, method='first').astype(int)
labels_sorted[labels_sorted["label"] == "Reckless"].assign(rank=ranks)[["ride_id", "rank", "label"]].sort_values("rank")

Total spectral energy AP = 0.6671

                                               ride_id  rank     label
18   08d6ca212bdc3aaf0d2437d2edcdfc4e59578e8a3bfb37...     1  Reckless
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     2  Reckless
376  c3e962b4175b9683364f6bdc16fcf78601d3efe32b32fa...     3  Reckless
490  fb684d4bc577c517182977f5c29508cb60b9ebf5c10286...     7  Reckless
325  a7ce7f3adb728eb0fe3b8641d5b928d419a3ebd6fd1db3...    12  Reckless
362  bc3a359722aa3e8335718c70d4ea1fd2f3d60764777c1c...   419  Reckless

In [11]:
ap_random_theoretical = y_true.mean()
print(f"Theoretical random AP = {ap_random_theoretical:.4f}")
sb.glue("GBG500_ap_random", float(ap_random_theoretical))

Theoretical random AP = 0.0120